// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function($scope) {
    return $scope.now = function() {
      return moment().format('LLLL');
    };
  };

  angular.module('diaa.meApp').controller('AboutmeCtrl', controller);

}).call(this);

/*
//@ sourceMappingURL=aboutme.map
*/
