// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('diaa.meApp').controller('CareerCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);
