// Generated by CoffeeScript 1.6.3
/* jshint -W093*/


(function() {
  "use strict";
  angular.module("diaa.meApp").controller("MainCtrl", function($scope) {
    return $scope.awesomeThings = ["HTML5 Boilerplate", "AngularJS", "Karma"];
  });

}).call(this);
