// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller;

  controller = function() {};

  angular.module("diaa.meApp").directive("layout", function() {
    return {
      templateUrl: "views/directives/layout.html",
      transclude: true,
      replace: true,
      scope: true,
      restrict: "E",
      controller: ["$scope", controller]
    };
  });

}).call(this);
