// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller;

  controller = function() {};

  angular.module("diaa.meApp").directive("navmenu", function() {
    return {
      templateUrl: "views/directives/navmenu.html",
      restrict: "E",
      controller: ["$scope", controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=navmenu.map
*/
